"""empty message

Revision ID: aa5c1a1ca615
Revises: 
Create Date: 2021-03-02 10:31:38.738474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5c1a1ca615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datatest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('d1', sa.String(length=64), nullable=True),
    sa.Column('d2', sa.String(length=64), nullable=True),
    sa.Column('d3', sa.DateTime(), nullable=True),
    sa.Column('d4', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datatest')
    # ### end Alembic commands ###
